<script setup lang="ts">
import {computed, nextTick, onMounted, onUnmounted, reactive, ref, watch} from 'vue'
import {api, endpoint, memory, stateLabel} from './api'
import InstanceLogs from './InstanceLogs.vue'
import InstanceEditor from './InstanceEditor.vue'
type Row=Record<string,any>
const props=defineProps<{identity:Row,platform:Row}>()
const emit=defineEmits<{navigate:[page:string,tab?:string],session:[id:string]}>()
const admin=computed(()=>props.identity.user?.role==='admin'&&props.identity.scopes?.includes('manage'))
const fleet=ref<Row>({instances:[],counts:{},warnings:[]}),metrics=ref<Row>({host:{},containers:[]}),kernels=ref<Row[]>([]),environments=ref<Row[]>([]),launchTemplates=ref<Row[]>([]),configTemplates=ref<Row[]>([])
const group=ref('native'),busy=ref(false),error=ref(''),notice=ref(''),modal=ref(''),row=ref<Row>({}),nameState=ref(''),preview=ref<Row>({pages:[],image:''}),previewError=ref(''),target=ref(''),address=ref(''),openMode=ref('current'),logs=ref<Row>({entries:[]})
const form=reactive<Row>({}),confirm=ref(''),customChecked=ref(false)
const managerCapabilities=ref<Row>({}),checkingManager=ref(false)
const editConfiguration=ref<Row>({})
const groups=[{id:'native',name:'本机原生'},{id:'fingerprint',name:'fingerprint-chromium'},{id:'cloak',name:'Cloak'}]
const rows=computed(()=>fleet.value.instances.filter((r:Row)=>r.kind===group.value))
const compatible=computed(()=>kernels.value.filter(k=>k.kind===form.kind))
const launches=computed(()=>launchTemplates.value.filter(t=>t.kind===form.kind))
const capability=computed(()=>kernels.value.find(k=>(k.binary||k.id)===form.binary))
const ready=computed(()=>form.kind==='cloak'?environments.value.some(e=>e.id===form.environment&&e.ready!==false)&&!!managerCapabilities.value.generation:(compatible.value.some(k=>(k.binary||k.id)===form.binary)||customChecked.value))
const supportingPlugins=computed(()=>form.kind==='cloak'||capability.value?.extensions==='automatic'||customChecked.value&&form.extensions==='automatic')
const addressDirty=ref(false)
let poll:ReturnType<typeof setInterval>,previewPoll:ReturnType<typeof setInterval>,nameTimer:ReturnType<typeof setTimeout>,generation=0,nameGeneration=0
async function work(fn:()=>Promise<void>){busy.value=true;error.value='';notice.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function refresh(){const [f,m]=await Promise.all([api<Row>('api/v1/fleet'),api<Row>('api/v1/metrics')]);fleet.value=f;metrics.value=m}
async function choices(){[kernels.value,environments.value,launchTemplates.value,configTemplates.value]=await Promise.all([api('api/v1/kernels'),api('api/v1/environments'),api('api/v1/launch-templates'),api('api/config/templates')])}
function selectKind(){customChecked.value=false;Object.assign(form,{environment:form.kind==='cloak'?(environments.value.find(e=>e.kind==='cloak'&&e.ready!==false)?.id||''):'native',binary:compatible.value[0]?.binary||compatible.value[0]?.id||'',launch_template_id:launches.value[0]?.id||'',fingerprint_seed:'',paths:''});selectLaunch()}
function selectLaunch(){const t=launches.value.find(t=>t.id===form.launch_template_id);if(t){form.headless=form.kind==='cloak'&&managerCapabilities.value.generation==='modern'?false:t.config.headless??false;if(!form.ephemeral)form.fingerprint_seed=t.config.fingerprint_seed??''}}
watch(()=>form.environment,async(environment)=>{managerCapabilities.value={};if(form.kind!=='cloak'||!environment)return;checkingManager.value=true;try{const r=await api<Row>('api/v1/fleet/capabilities?environment='+encodeURIComponent(environment));if(form.environment===environment){managerCapabilities.value=r;if(r.generation==='modern')form.headless=false}}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{checkingManager.value=false}})
async function createDialog(){await work(async()=>{await choices();Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,{kind:group.value,name:'',ephemeral:false,headless:false,no_sandbox:false,template_id:'',notes:'',paths:''});selectKind();nameState.value='';modal.value='create'})}
async function checkBinary(){await work(async()=>{const r=await api<Row>('api/v1/kernels/check','POST',{binary:form.binary});Object.assign(form,{binary:r.binary,extensions:r.extensions});customChecked.value=true;if(!kernels.value.some(k=>k.binary===r.binary))kernels.value.push(r)})}
async function checkName(){const id=++nameGeneration,name=form.name,environment=form.environment;nameState.value='';if(!name.trim()||!environment)return;try{const r=await api<Row>(`api/v1/fleet/name?name=${encodeURIComponent(name)}&environment=${encodeURIComponent(environment)}`);if(id===nameGeneration)nameState.value=r.available?'可用':'已存在'}catch{if(id===nameGeneration)nameState.value='提交时校验'}}
watch(()=>[form.name,form.environment],()=>{++nameGeneration;nameState.value='';clearTimeout(nameTimer);nameTimer=setTimeout(checkName,350)})
watch(()=>form.ephemeral,()=>{form.fingerprint_seed='';selectLaunch()})
async function create(){await work(async()=>{const body:Row={name:form.name,kind:form.kind,environment:form.environment,ephemeral:form.ephemeral,launch_template_id:form.launch_template_id,template_id:form.template_id,headless:form.kind==='cloak'&&managerCapabilities.value.generation==='modern'?false:form.headless,notes:form.notes};if(form.kind!=='cloak')Object.assign(body,admin.value?{binary:form.binary,no_sandbox:form.no_sandbox}:{kernel_id:form.binary});if(form.kind!=='native'&&form.fingerprint_seed!=='')body.fingerprint_seed=Number(form.fingerprint_seed);if(supportingPlugins.value&&form.paths.trim())body.extension_paths=form.paths.split(/\r?\n/).map((p:string)=>p.trim()).filter(Boolean);await api('api/v1/fleet/create','POST',body,{'Idempotency-Key':crypto.randomUUID()});modal.value='';notice.value='实例已创建，可以启动';await refresh()})}
async function control(r:Row,action:string){await work(async()=>{const result=await api<Row>('api/v1/fleet/action','POST',{ref:r.ref,action});if(result.session_id)emit('session',result.session_id);notice.value=result.deleted?'临时实例已回收':action==='stop'?'已停止，登录态保留':'实例已启动';await refresh()})}
async function view(r:Row){row.value=r;target.value='';preview.value={pages:[],image:''};previewError.value='';addressDirty.value=false;modal.value='preview';await capture();clearInterval(previewPoll);previewPoll=setInterval(()=>{if(modal.value==='preview'&&!document.hidden)void capture()},2500)}
async function capture(){if(modal.value!=='preview')return;const id=++generation,ref=row.value.ref,wanted=target.value;try{const data=await api<Row>(`api/v1/fleet/inspect?ref=${encodeURIComponent(ref)}&target=${encodeURIComponent(wanted)}`);if(id!==generation||modal.value!=='preview'||ref!==row.value.ref)return;preview.value=data;target.value=data.target;if(!addressDirty.value)address.value=data.pages.find((p:Row)=>p.targetId===data.target)?.url||address.value;previewError.value=''}catch(e){if(id===generation)previewError.value=e instanceof Error?e.message:String(e)}}
async function switchTab(id:string){target.value=id;addressDirty.value=false;await capture()}
async function navigate(){await work(async()=>{++generation;const result=await api<Row>('api/v1/fleet/navigate','POST',{ref:row.value.ref,target:target.value,url:address.value,mode:openMode.value});target.value=result.target;addressDirty.value=false;await capture()})}
async function showLogs(r:Row){await work(async()=>{row.value=r;logs.value=await api(`api/v1/fleet/logs?ref=${encodeURIComponent(r.ref)}`);modal.value='logs'})}
async function edit(r:Row){await work(async()=>{const [,configuration]=await Promise.all([choices(),api<Row>('api/v1/fleet/configuration?ref='+encodeURIComponent(r.ref))]);row.value=r;editConfiguration.value=configuration;modal.value='edit'})}
async function saveEdit(changes:Row){await work(async()=>{await api('api/v1/fleet/edit','POST',{ref:row.value.ref,changes});modal.value='';await refresh();notice.value='实例配置已保存，浏览器数据保留，下次启动生效'})}
async function remove(){await work(async()=>{await api('api/v1/fleet/delete','POST',{ref:row.value.ref,confirm:confirm.value});modal.value='';await refresh();notice.value='实例及登录态已删除'})}
async function copyConnection(){try{await navigator.clipboard.writeText(JSON.stringify({...row.value.connection,service_url:endpoint('')},null,2));notice.value='连接信息已复制'}catch{error.value='无法访问剪贴板，请手动复制下方连接信息'}}
function close(){++generation;modal.value='';clearInterval(previewPoll)}
function keyboard(e:KeyboardEvent){if(e.key==='Escape')close();if(e.key==='Tab'&&modal.value){const nodes=[...document.querySelectorAll<HTMLElement>('.fleet-dialog input:not(:disabled),.fleet-dialog select:not(:disabled),.fleet-dialog textarea,.fleet-dialog button:not(:disabled)')].filter(n=>n.offsetParent!==null);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}
watch(modal,async v=>{if(v){await nextTick();document.querySelector<HTMLElement>('.fleet-dialog input,.fleet-dialog button')?.focus()}else{++generation;clearInterval(previewPoll)}})
onMounted(async()=>{await work(refresh);poll=setInterval(()=>{if(!document.hidden&&!busy.value)void refresh().catch(()=>{})},5000);document.addEventListener('keydown',keyboard)})
onUnmounted(()=>{++generation;clearInterval(poll);clearInterval(previewPoll);clearTimeout(nameTimer);document.removeEventListener('keydown',keyboard)})
</script>

<template>
  <div class="page-heading"><div><div class="eyebrow">BROWSER FLEET</div><h1>浏览器实例<span class="dot">.</span></h1><p>长期实例保留登录态；临时实例在结束后回收。</p></div><button :disabled="busy" @click="work(refresh)">↻ 刷新</button></div>
  <p v-if="error" class="alert danger" role="alert">{{error}}</p><p v-if="notice" class="alert success" role="status">{{notice}}</p>
  <div class="fleet-stats">
    <article v-for="item in [{key:'all',name:'全部实例'},{key:'running',name:'运行中'},{key:'persistent',name:'长期实例'},{key:'temporary',name:'临时实例'}]" :key="item.key" class="stat" :class="item.key==='running'?'blue':''"><span>{{item.name}}</span><strong>{{fleet.counts[item.key]??'—'}}</strong></article>
    <article class="stat yellow"><div class="card-head"><span>主机 CPU</span><button v-if="admin" class="text-button" @click="emit('navigate','service','alerts')">设置阈值 ↗</button></div><strong>{{metrics.host.cpu_percent==null?'—':metrics.host.cpu_percent.toFixed(1)+'%'}}</strong><small>Sleight 执行主机</small></article>
    <article class="stat"><div class="card-head"><span>主机内存</span><button v-if="admin" class="text-button" @click="emit('navigate','service','alerts')">设置阈值 ↗</button></div><strong>{{metrics.host.memory_percent==null?'—':metrics.host.memory_percent.toFixed(1)+'%'}}</strong><small>{{memory(metrics.host.memory_used)}} / {{memory(metrics.host.memory_total)}}</small></article>
  </div>
  <p v-for="warning in fleet.warnings" :key="warning" class="alert yellow">{{warning}}</p>
  <div class="toolbar"><button class="primary" :disabled="busy" @click="createDialog">＋ 新建实例</button><small>停止长期实例保留登录态，删除会清空数据。回收失败仍计入临时实例。</small></div>
  <div class="segmented kernel-tabs" role="tablist" aria-label="内核类型"><button v-for="g in groups" :key="g.id" role="tab" :aria-selected="group===g.id" :class="{primary:group===g.id}" @click="group=g.id">{{g.name}} · {{fleet.instances.filter((r:Row)=>r.kind===g.id).length}}</button></div>
  <div v-if="!rows.length" class="panel empty"><h2>还没有{{groups.find(g=>g.id===group)?.name}}实例。</h2><p>创建一个长期实例用于登录，或通过 SDK / MCP 创建临时实例。</p><button :disabled="busy" @click="createDialog">新建实例</button></div>
  <div class="fleet fleet-four"><article v-for="r in rows" :key="r.ref" class="panel browser"><div class="card-head"><h2>{{r.name}}</h2><span class="badge" :class="r.status==='running'?'green':'neutral'">{{stateLabel[r.status]||r.status}}</span></div><div class="card-tags"><span>{{r.ephemeral?'临时实例':'长期实例'}}</span><span>{{r.user_name}}</span></div><dl><div><dt>内核</dt><dd>{{r.kernel}} {{r.version}}</dd></div><div><dt>环境</dt><dd>{{r.environment==='native'?'本机':r.environment}}</dd></div><div><dt>实例 ID</dt><dd class="mono" :title="r.id">{{r.id.slice(0,12)}}</dd></div><div><dt>端口 / PID</dt><dd>{{r.port||'—'}} / {{r.pid||'—'}}</dd></div><div><dt>进程内存</dt><dd>{{memory(r.memory_bytes)}}</dd></div><div v-if="r.notes"><dt>备注</dt><dd>{{r.notes}}</dd></div></dl><div class="card-actions"><button :disabled="busy||['starting','creating','cleaning','cleanup_pending'].includes(r.status)" :class="r.status==='running'?'':'primary'" @click="control(r,r.status==='running'?'stop':'start')">{{r.status==='running'?'停止':'启动'}}</button><button :disabled="busy||r.ephemeral||r.status!=='running'" :title="r.ephemeral?'临时实例停止后请重新创建':''" @click="control(r,'restart')">重启</button><button :disabled="busy||r.status!=='running'" @click="view(r)">查看实例</button><button :disabled="busy" @click="showLogs(r)">日志</button></div><div class="card-actions secondary-actions"><button class="text-button" @click="row=r;modal='details'">连接详情</button><button class="text-button" :disabled="busy||!['stopped','idle'].includes(r.status)" :title="['stopped','idle'].includes(r.status)?'修改名称和启动配置':'请先停止实例，再编辑配置'" @click="edit(r)">编辑实例</button><button class="text-button danger-text" :disabled="busy" @click="row=r;confirm='';modal='delete'">删除</button></div></article></div>
  <details v-if="metrics.containers.length" class="panel environment container-metrics"><summary>Manager 容器资源</summary><p v-for="m in metrics.containers" :key="m.id">{{m.name}} · {{m.unavailable?'不可连接':`CPU ${m.cpu_percent.toFixed(1)}% / 内存 ${m.memory_percent.toFixed(1)}%`}}<small v-if="!m.unavailable"> CPU 相对于容器 {{m.cpu_limit}} 核限额</small></p></details>
  <div v-if="modal" class="overlay" @click.self="close"><section class="panel dialog fleet-dialog" :class="{viewer:modal==='preview','instance-log-dialog':modal==='logs'}" role="dialog" aria-modal="true" :aria-label="modal==='create'?'新建浏览器实例':row.name"><button class="close" aria-label="关闭弹窗" @click="close">×</button>
    <form v-if="modal==='create'" @submit.prevent="create"><h2>新建浏览器实例</h2><label>创建类型<select v-model="form.kind" @change="selectKind"><option v-for="g in groups" :key="g.id" :value="g.id">{{g.name}}</option></select></label><label v-if="form.kind==='cloak'">Manager 环境<select v-model="form.environment"><option value="">选择已部署环境</option><option v-for="e in environments.filter(e=>e.kind==='cloak'&&e.ready!==false)" :key="e.id" :value="e.id">{{e.name}}</option></select></label>
      <label v-if="form.kind!=='cloak'&&compatible.length">浏览器内核<select v-model="form.binary"><option v-for="k in compatible" :key="k.binary||k.id" :value="k.binary||k.id">{{k.name}} {{k.version}} · {{k.extensions==='automatic'?'自动加载插件':k.extensions==='manual'?'手动安装插件':'插件能力待验证'}}</option></select></label>
      <div v-if="!ready" class="empty effective"><h3>{{checkingManager?'正在检查 Manager 连接…':'先准备运行环境。'}}</h3><p>{{form.kind==='cloak'?'先部署 Cloak Manager，再创建浏览器。':'还未发现此内核，请先安装或检查可执行文件。'}}</p><button type="button" @click="close();emit('navigate','environments')">去部署环境 →</button></div>
      <details v-if="admin&&form.kind!=='cloak'"><summary>指定已安装的可执行文件</summary><label>可执行文件<input v-model="form.binary" placeholder="完整可执行文件路径" @input="customChecked=false"></label><button type="button" :disabled="busy||!form.binary" @click="checkBinary">检查内核</button></details>
      <template v-if="ready"><label>创建模板<select v-model="form.launch_template_id" @change="selectLaunch"><option v-for="t in launches" :key="t.id" :value="t.id">{{t.name}}</option></select></label><p class="fine">{{launches.find(t=>t.id===form.launch_template_id)?.note}}</p><button v-if="admin&&form.kind==='cloak'" type="button" class="text-button" @click="close();emit('navigate','service','launch-templates')">＋ 新增自定义 Cloak 模板 →</button><label>实例名称<input v-model="form.name" required maxlength="100" placeholder="给实例一个容易识别的名字"></label><small :class="nameState==='已存在'?'danger-text':''">{{nameState==='已存在'?'同一环境中已有此名称':nameState}}</small><label>使用方式<select v-model="form.ephemeral"><option :value="false">长期实例 · 保留 Cookie 和登录态</option><option :value="true">临时实例 · 结束后删除数据</option></select></label><label v-if="form.kind!=='native'">指纹种子<input v-model="form.fingerprint_seed" type="number" min="1" max="2147483647" :placeholder="form.ephemeral?'留空，每个临时实例随机生成':'留空使用内核默认值'"></label><p v-if="form.kind==='cloak'&&managerCapabilities.generation==='modern'" class="fine">Manager 0.1.x 使用有界面浏览器，由容器中的显示服务渲染；不支持每个实例设置无头模式。</p><label v-if="form.kind!=='cloak'||managerCapabilities.generation!=='modern'" class="check"><input v-model="form.headless" type="checkbox">无头模式（不弹出浏览器窗口）</label><label v-if="form.kind!=='cloak'&&platform.os==='Linux'" class="check"><input v-model="form.no_sandbox" type="checkbox">容器 / root 用户使用 no-sandbox</label><label>插件与代理模板<select v-model="form.template_id"><option value="">用户默认配置</option><option v-for="t in configTemplates" :key="t.id" :value="t.id">{{t.name}}</option></select></label><p v-if="form.kind==='native'&&!supportingPlugins" class="fine">{{capability?.extension_note||'自动加载能力未确认。'}} 有界面启动后，在 chrome://extensions 或 edge://extensions 开启开发者模式安装插件。插件只保存在此实例。</p><label v-if="supportingPlugins&&admin">覆盖插件目录（可选）<textarea v-model="form.paths" rows="2" placeholder="每行一个目录，留空使用模板"></textarea></label><label>备注<textarea v-model="form.notes" rows="2" maxlength="1000" placeholder="用途、登录账号说明；请勿填写密码"></textarea></label></template><p v-if="error" class="alert danger">{{error}}</p><div class="dialog-actions"><button type="button" @click="close">取消</button><button class="primary" :disabled="busy||!ready||!form.name.trim()||nameState==='已存在'">创建实例</button></div></form>
    <template v-if="modal==='preview'"><h2>{{row.name}} · 查看实例</h2><div class="preview-tabs" role="tablist" aria-label="浏览器页面"><button v-for="p in preview.pages" :key="p.targetId" role="tab" :aria-selected="target===p.targetId" :class="{primary:target===p.targetId}" :title="p.url" @click="switchTab(p.targetId)">{{p.title||'未命名页面'}}<small>{{p.targetId}}</small></button></div><form class="navigate-form" @submit.prevent="navigate"><input v-model="address" @input="addressDirty=true" aria-label="网址" placeholder="输入网址，例如 https://example.com" required><select v-model="openMode" aria-label="打开方式"><option value="current">当前页面</option><option value="tab">新标签页</option><option value="window">新窗口</option></select><button :disabled="busy" class="primary">打开</button></form><p v-if="previewError" class="alert yellow" role="alert">{{previewError}}<button @click="capture">重试</button></p><img v-if="preview.image" :src="preview.image" alt="浏览器当前页面截图"><p v-else>正在获取页面；没有标签页时可先打开网址。</p><div class="card-actions"><span class="fine">只读截图，每 2.5 秒刷新；网址操作由此实例执行。</span><a v-if="row.kind==='cloak'&&admin" :href="endpoint('viewer/'+row.environment+'/')" target="_blank" rel="noopener">打开官方 Manager 监控 ↗</a></div></template>
    <InstanceLogs v-if="modal==='logs'" :key="row.ref" :name="row.name" :entries="logs.entries" :busy="busy" :error="error" @refresh="showLogs(row)" />
    <InstanceEditor v-if="modal==='edit'" :key="row.ref" :configuration="editConfiguration" :templates="configTemplates" :launches="launchTemplates" :admin="admin" :platform="platform" :busy="busy" :error="error" @save="saveEdit" @cancel="close" />
    <template v-if="modal==='details'"><h2>{{row.name}} · 连接信息</h2><p>{{row.ephemeral?'临时实例':'长期实例'}} · 用户 {{row.user_name}} · {{row.environment}}</p><pre>{{JSON.stringify({...row.connection,service_url:endpoint('')},null,2)}}</pre><p class="fine">代码和 MCP 使用用户执行 token 调用 Sleight API。此处不显示 token；远端端口不是本机直连地址。</p><p v-if="row.notes">{{row.notes}}</p><button @click="copyConnection">复制连接信息</button></template>
    <form v-if="modal==='delete'" @submit.prevent="remove"><h2>删除「{{row.name}}」？</h2><p class="alert yellow">会删除 Cookie 和登录态。先停止运行会话再删除；长期实例只需停止即可保留数据。</p><label>输入完整实例名确认<input v-model="confirm" required :placeholder="row.name"></label><p v-if="error" class="alert danger">{{error}}</p><div class="dialog-actions"><button type="button" @click="close">取消</button><button class="danger" :disabled="busy||confirm!==row.name">确认删除</button></div></form>
  </section></div>
</template>
